import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {initMateriaux,materiauxRoute} from '../worker/materiaux.js';
const db=new DatabaseSync(':memory:');
const sql={exec(query,...args){if(!args.length&&query.startsWith('CREATE')){db.exec(query);return{toArray:()=>[]}}const st=db.prepare(query);return{toArray:()=>st.all(...args)}}};
// The production API executes SQL eagerly, including mutations.
sql.exec=(query,...args)=>{if(!args.length&&query.startsWith('CREATE')){db.exec(query);return{toArray:()=>[]}}const st=db.prepare(query);const rows=st.all(...args);return{toArray:()=>rows}};
initMateriaux(sql);
const store={sql,one:(s,...a)=>sql.exec(s,...a).toArray()[0],teacher(req){if(req.headers.get('cookie')!=='test=teacher')throw Error('Unauthorized')},limited(){}};
const call=(path,{body,token,teacher,origin}={})=>materiauxRoute(store,new Request('https://example.test/api/evaluations'+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{}),...(teacher?{cookie:'test=teacher'}:{}),...(origin?{origin}:{})},body:body===undefined?undefined:JSON.stringify(body)}),path);
let r=await call('/materiaux/create',{body:{}});assert.equal(r.status,201);const {token,workbook}=await r.json();assert.match(token,/^[A-F0-9]{32}$/);
assert.equal((await call('/materiaux/state')).status,401);
assert.equal((await call('/materiaux/state',{token:'F'.repeat(32)})).status,401);
let payload={revision:0,answers:{s1_idea_v2:'Augmenter l’épaisseur de la planche',s1_need:'Franchir la rivière',s4_e1_why:'Test réussi'},lesson:4,guided:false};
r=await call('/materiaux/save',{body:payload,token});assert.equal(r.status,200);assert.equal((await r.json()).revision,1);
r=await call('/materiaux/state',{token});assert.equal((await r.json()).answers.s1_need,'Franchir la rivière');
assert.equal((await call('/materiaux/save',{body:payload,token})).status,409);
assert.equal((await call('/materiaux/save',{body:{...payload,revision:1,answers:{s1_need:'a'.repeat(2501)}},token})).status,400);
assert.equal((await call('/materiaux/save',{body:{...payload,revision:1},token,origin:'https://evil.test'})).status,403);
r=await call('/materiaux/submit',{body:{...payload,revision:1},token});assert.equal(r.status,200);assert.ok((await r.json()).submitted);
await assert.rejects(()=>call('/teacher/materiaux'),/Unauthorized/);
r=await call('/teacher/materiaux',{teacher:true});const summary=await r.json();assert.equal(summary.workbooks.length,1);assert.ok(!JSON.stringify(summary).includes(token));assert.ok(!JSON.stringify(summary).includes('Franchir'));
r=await materiauxRoute(store,new Request('https://example.test/api/evaluations/teacher/materiaux/review?id='+workbook.id,{headers:{cookie:'test=teacher'}}),'/teacher/materiaux/review');assert.equal((await r.json()).answers.s1_need,'Franchir la rivière');
r=await call('/materiaux/save',{body:{...payload,revision:2},token});assert.equal((await r.json()).submitted,null);
assert.equal((await call('/teacher/materiaux/delete',{teacher:true,body:{id:workbook.id}})).status,400);
assert.equal((await call('/teacher/materiaux/delete',{teacher:true,body:{id:workbook.id,confirm:true}})).status,200);
assert.equal((await call('/materiaux/state',{token})).status,401);
const guidedCreate=await call('/materiaux/create',{body:{guided:true}});assert.equal(guidedCreate.status,201);
const guidedToken=(await guidedCreate.json()).token;
assert.equal((await call('/materiaux/save',{token:guidedToken,body:{revision:0,answers:{s1_use:'Franchir un obstacle'},lesson:1,guided:true}})).status,200);
assert.equal((await call('/materiaux/save',{token:guidedToken,body:{revision:1,answers:{},lesson:1,guided:false}})).status,400);
console.log('PASS: reprise, sauvegarde, conflits, limites, origine, transmission, protection professeur, suppression');
// Progressive opening is enforced on the server, without changing answer revisions.
await assert.rejects(()=>call('/teacher/materiaux/access',{body:{classe:'503',through:2}}),/Unauthorized/);
const extra=await (await call('/materiaux/create',{body:{guided:true}})).json();
const testId=extra.workbook.id, testToken=extra.token;
assert.equal((await call('/teacher/materiaux/class',{teacher:true,body:{id:testId,classe:'503'}})).status,200);
assert.equal((await call('/teacher/materiaux/access',{teacher:true,body:{classe:'503',through:2}})).status,200);
let state=await (await call('/materiaux/state',{token:testToken})).json();assert.equal(state.openThrough,2);assert.equal(state.revision,0);assert.equal(state.classe,undefined);
let draft={revision:0,answers:{s1_use:'Franchir un obstacle',s4_real:'Pas encore'},lesson:4,guided:true};
assert.equal((await call('/materiaux/save',{token:testToken,body:draft})).status,403);
assert.equal((await call('/materiaux/save',{token:testToken,body:{...draft,answers:{s1_use:'Franchir un obstacle'},lesson:2}})).status,200);
assert.equal((await call('/teacher/materiaux/access',{teacher:true,body:{classe:'503',through:4}})).status,200);
state=await (await call('/materiaux/save',{token:testToken,body:{...draft,revision:1}})).json();assert.equal(state.revision,2);
await call('/teacher/materiaux/access',{teacher:true,body:{classe:'503',through:1}});
state=await (await call('/materiaux/save',{token:testToken,body:{...draft,revision:2,answers:{...draft.answers,s1_use:'Réponse ajustée'}}})).json();
assert.equal(state.lesson,1);assert.equal(state.answers.s4_real,'Pas encore');assert.equal(state.openThrough,1);
assert.equal((await call('/materiaux/save',{token:testToken,body:{...draft,revision:3,answers:{s1_use:'Réponse ajustée'}}})).status,403);
assert.equal((await call('/teacher/materiaux/access',{teacher:true,body:{classe:'503',through:0}})).status,400);
assert.equal((await call('/teacher/materiaux/class',{teacher:true,body:{id:testId,classe:'<script>'}})).status,400);
const listed=await (await call('/teacher/materiaux',{teacher:true})).json();assert.equal(listed.workbooks.find(w=>w.id===testId).classe,'503');
assert.equal((await (await call('/materiaux/access',{token:testToken})).json()).openThrough,1);
assert.equal((await (await call('/materiaux/state',{token:guidedToken})).json()).openThrough,4);
console.log('PASS: ouverture par classe, accès professeur, refus de modification des séances fermées, conservation des réponses et isolation des classes');
