"""Contenus sources des séquences de technologie."""

SOURCES = [
    ("Programme de technologie du cycle 4", "https://www.education.gouv.fr/sites/default/files/document/Annexe%20%E2%80%94%20Programme%20de%20technologie%20du%20cycle%204-368016.pdf"),
    ("Lettre de rentrée STI, Nouvelle-Calédonie : accompagnement", "https://www.ac-noumea.nc/IMG/pdf/2025_lettre_de_rentree_sti.pdf"),
    ("Lettre de rentrée STI, Nouvelle-Calédonie : mise en œuvre", "https://s2i2a.ac-noumea.nc/spip.php?article112="),
    ("Ressources nationales de technologie au cycle 4", "https://eduscol.education.gouv.fr/5745/ressources-d-accompagnement-du-programme-de-technologie-au-cycle-4"),
    ("DEPP, CEDRE technologie : compétences et évaluation", "https://www.education.gouv.fr/sites/default/files/document/cedre-sciences-coll-ge-technologie-2024-518699.pdf"),
]

# Blocs communs : p = texte ; h = intertitre ; q = réponse rédigée ;
# table = tableau documentaire ; answer_table = tableau à compléter ;
# sim = expérience dans le navigateur ; diagram = schéma fonctionnel.
LESSONS = [
{
 "level":"5e", "slug":"objet-du-quotidien", "title":"Un objet, un besoin, des solutions",
 "question":"Comment expliquer les choix de conception d'un objet du quotidien ?",
 "objective":"Identifier l'usage d'un objet, relier trois composants à leur rôle et justifier une amélioration.",
 "prerequisites":"Savoir ouvrir un fichier et écrire quelques phrases. La distinction entre objet et matériau est reprise au lancement.",
 "programme":"Compétences travaillées : étude des besoins et des usages ; description de la constitution d'un objet ; identification de matériaux et de contraintes.",
 "success":["Une fonction d'usage formulée avec un verbe à l'infinitif.","Trois composants associés à leur rôle et à leur matériau.","Une amélioration justifiée par une contrainte précise."],
 "timeline":[
   ["0-5 min","Lancement","Demander : « Une selle est-elle un matériau ? À quoi sert un vélo ? » Faire distinguer besoin, composant et matériau."],
   ["5-10 min","Choix et lecture","Ouvrir l'activité 5e, choisir un des trois objets et lire sa fiche. Faire reformuler la production attendue."],
   ["10-28 min","Analyse","Répondre aux questions 1 à 3. En binôme, changer de secrétaire à mi-parcours. Questionner les élèves sur le rôle des pièces."],
   ["28-38 min","Conception","Traiter les contraintes et proposer une amélioration. Exiger une justification, pas seulement un goût personnel."],
   ["38-48 min","Mise en commun","Comparer deux choix d'objets ; compléter ensemble la synthèse."],
   ["48-55 min","Bilan individuel","Répondre au billet de sortie, puis télécharger les réponses. Avec un PC par binôme, chacun répond dans sa case personnelle."],
 ],
 "pages":[
   [
    {"type":"p","text":"Choisis un objet parmi les trois fiches ci-dessous. Ce sont des modèles d'étude simplifiés : les matériaux indiqués ne décrivent pas tous les modèles vendus dans le commerce. Toutes les informations nécessaires sont fournies."},
    {"type":"h","text":"Les trois objets au choix"},
    {"type":"table","headers":["Objet","Composants et matériaux du modèle","Fonctionnement et attente"],"rows":[
      ["Vélo de ville","Cadre : aluminium. Chaîne : acier. Pneus : caoutchouc. À volume égal, l'aluminium est moins massif que l'acier.","L'utilisateur pédale ; la chaîne transmet le mouvement vers la roue arrière. Le cadre soutient l'ensemble ; les pneus assurent le contact avec le sol. L'utilisateur souhaite un vélo facile à transporter."],
      ["Lampe de bureau rechargeable","Socle : acier. Coque : plastique ABS. Diffuseur : polycarbonate, un plastique translucide.","La batterie fournit de l'énergie électrique à une LED qui émet de la lumière. Le socle stabilise la lampe ; la coque protège les éléments ; le diffuseur répartit la lumière. L'utilisateur souhaite éclairer son bureau sans être ébloui."],
      ["Ventilateur USB","Pales : plastique ABS. Grille : acier. Socle : acier.","Le port USB fournit l'énergie électrique au moteur qui fait tourner les pales. Les pales mettent l'air en mouvement ; la grille empêche le contact direct avec elles ; le socle stabilise l'appareil. L'utilisateur souhaite un appareil stable et protecteur."],
    ]},
    {"type":"choice","id":"objet","label":"Mon objet d'étude","options":["Choisir un objet","Vélo de ville","Lampe de bureau rechargeable","Ventilateur USB"]},
    {"type":"q","id":"q1","label":"1. À quel besoin répond cet objet ? Qui l'utilise ?","lines":2},
    {"type":"q","id":"q2","label":"2. Écris sa fonction d'usage avec un verbe à l'infinitif : « Cet objet permet de... »","lines":2},
    {"type":"p","text":"Un composant est une pièce ou un élément de l'objet. Un matériau est la matière qui le constitue : par exemple, le pneu est un composant et le caoutchouc est son matériau."},
   ],
   [
    {"type":"h","text":"Expliquer et améliorer"},
    {"type":"answer_table","id":"q3","label":"3. Analyse trois composants de l'objet choisi.","headers":["Composant","Rôle dans l'objet","Matériau"],"rows":3},
    {"type":"q","id":"q4","label":"4. Repère une contrainte dans la fiche. Explique comment une pièce ou un matériau permet d'y répondre.","lines":3},
    {"type":"q","id":"q5","label":"5. Propose une amélioration pour un utilisateur précis. Justifie son intérêt et cite un inconvénient possible.","lines":3},
    {"type":"q","id":"synthese","label":"Synthèse à compléter lors de la mise en commun : la fonction d'usage indique à quoi sert l'________. Il est constitué de __________ fabriqués dans des __________. Les choix de conception doivent respecter des __________.","lines":2},
    {"type":"p","text":"Défi facultatif : indique un test concret pour vérifier si ton amélioration répond réellement à l'attente de l'utilisateur."},
    {"type":"exit","id":"bilan","label":"Billet de sortie individuel : un casque protège la tête. Donne sa fonction d'usage, puis cite un composant et un matériau possible pour ce composant.","lines":2},
   ],
 ],
 "correction":[
  ["Q1-Q2, vélo","Besoin de déplacement ; cycliste. Fonction : permettre de se déplacer grâce au pédalage. « Rouler » seul reste trop peu précis."],
  ["Q1-Q2, lampe","Besoin de voir pour lire ou travailler ; personne à son bureau. Fonction : éclairer une zone de travail."],
  ["Q1-Q2, ventilateur","Besoin de confort thermique ; personne près du bureau. Fonction : mettre l'air en mouvement vers l'utilisateur. Il ne refroidit pas nécessairement l'air de la pièce."],
  ["Q3, vélo","Cadre / soutenir et relier les éléments / aluminium ; chaîne / transmettre le mouvement / acier ; pneus / assurer le contact avec le sol / caoutchouc."],
  ["Q3, lampe","Socle / stabiliser / acier ; coque / protéger / ABS ; diffuseur / répartir la lumière / polycarbonate."],
  ["Q3, ventilateur","Pales / mettre l'air en mouvement / ABS ; grille / protéger contre le contact avec les pales / acier ; socle / stabiliser / acier."],
  ["Q4","Vélo : masse limitée pour le transport, l'aluminium est une solution possible. Lampe : limiter l'éblouissement grâce au diffuseur. Ventilateur : stabilité par le socle et protection par la grille. Accepter tout lien exact expliqué."],
  ["Q5","Exemples : cadre pliant pour transporter le vélo (coût/complexité) ; réglage de l'intensité pour adapter la lampe (coût/électronique) ; socle plus large pour le ventilateur (encombrement). Ne pas imposer une solution unique."],
  ["Synthèse","objet ; composants ; matériaux ; contraintes."],
  ["Billet de sortie","Protéger la tête ; coque extérieure en plastique ou couche intérieure de mousse. Accepter toute association techniquement plausible entre une pièce et sa matière."],
 ],
 "aides":["Faire entourer un nom de pièce et souligner un nom de matériau dans la fiche.","Donner l'amorce : « La pièce ... sert à ... ; elle est fabriquée en ... ».","Pour la contrainte, faire relire la dernière phrase de la fiche choisie."],
 "vigilance":"Ne pas confondre fonction d'usage, solution technique et jugement esthétique. Une propriété supposée d'un matériau doit être reliée au besoin ; ne pas présenter un choix comme universellement meilleur.",
 "assessment":"Bilan formatif, éventuellement /4 : fonction d'usage 2 points ; composant identifié 1 point ; matériau cohérent associé 1 point. En binôme, évaluer les deux billets séparément.",
 "next":"Comparer deux solutions répondant au même besoin à l'aide de critères et de données mesurables.",
},
{
 "level":"4e", "slug":"eclairage-automatique", "title":"Allumer seulement quand c'est utile",
 "question":"Comment commander un éclairage avec deux informations ?",
 "objective":"Modifier une règle de commande et vérifier son comportement à l'aide de plusieurs essais, y compris au seuil.",
 "prerequisites":"Comprendre une comparaison de nombres. Les mots capteur, condition et action sont définis dans la fiche.",
 "programme":"Compétences travaillées : données provenant de capteurs, algorithme de commande, modification et mise au point d'un programme. Cette séance prépare un travail ultérieur dans un environnement de programmation par blocs.",
 "success":["La lampe s'allume uniquement si les deux conditions demandées sont remplies.","Cinq essais sont renseignés, dont celui à la valeur limite 30.","Le rôle de ET est expliqué à l'aide d'un contre-exemple."],
 "timeline":[
   ["0-5 min","Situation-problème","Demander : « Faut-il éclairer un couloir vide ? Un couloir déjà très lumineux ? »"],
   ["5-10 min","Compréhension","Lire la règle attendue et identifier les deux capteurs et l'actionneur. Montrer l'ouverture du fichier sans résoudre le programme."],
   ["10-22 min","Observer l'erreur","Conserver la règle initiale avec OU ; prévoir puis tester les cinq cas. Chaque binôme identifie au moins un résultat non conforme."],
   ["22-35 min","Corriger et tester","Modifier la règle, cliquer sur Appliquer, recommencer les cinq essais et compléter l'algorithme."],
   ["35-44 min","Justifier","Expliquer ET, étudier exactement 30 puis un seuil à 50. Garder le seuil à 30 pour le bilan."],
   ["44-50 min","Synthèse","Formaliser capteur, traitement, actionneur et condition ; faire justifier un cas limite."],
   ["50-55 min","Bilan individuel","Traiter le billet de sortie sans aide du partenaire puis télécharger le travail."],
 ],
 "pages":[
   [
    {"type":"p","text":"Dans un couloir, la lampe doit s'allumer seulement si une présence est détectée ET si le niveau de luminosité est strictement inférieur à 30. Sinon elle doit être éteinte. Le simulateur utilise un indice de luminosité de 0 à 100 : 0 signifie très sombre et 100 très lumineux. Cet indice est une donnée pédagogique, pas une mesure en lux."},
    {"type":"table","headers":["Élément","Rôle"],"rows":[["Capteur de luminosité","Fournir une valeur numérique de 0 à 100."],["Capteur de présence","Fournir une information : présence ou absence."],["Carte programmable","Appliquer la règle de commande."],["Lampe LED","Émettre de la lumière lorsqu'elle est alimentée."]]},
    {"type":"q","id":"q1","label":"1. Quelles sont les deux informations nécessaires pour décider d'allumer ? Quel élément réalise l'action ?","lines":2},
    {"type":"sim","name":"light"},
    {"type":"answer_table","id":"essais","label":"2. Avec la règle initiale OU, prévois puis observe le résultat. Après correction, complète la dernière colonne.","headers":["Luminosité / présence","Prévision avec OU","Observation avec OU","Après correction"],"fixed":["10 / oui","10 / non","80 / oui","80 / non","30 / oui"],"rows":5},
    {"type":"p","text":"Sur papier, déroule mentalement les conditions. Sur PC, règle chaque situation et relève l'état de la lampe. Une seule situation ne suffit pas à valider un programme."},
   ],
   [
    {"type":"h","text":"Corriger et expliquer"},
    {"type":"q","id":"q3","label":"3. Cite un essai où la règle initiale ne respecte pas le besoin. Explique pourquoi.","lines":2},
    {"type":"q","id":"q4","label":"4. Corrige la règle, puis écris l'algorithme complet : SI ... ALORS ... SINON ... .","lines":3},
    {"type":"q","id":"q5","label":"5. Avec la règle corrigée, que se passe-t-il exactement à 30 si une personne est présente ? Justifie avec le signe de comparaison.","lines":2},
    {"type":"q","id":"q6","label":"6. Si le seuil passe de 30 à 50, que se passe-t-il pour une luminosité de 40 avec une présence ? Explique ce qui change.","lines":2},
    {"type":"q","id":"synthese","label":"Synthèse : les capteurs fournissent des __________. Le programme les __________. La lampe est un __________. Avec ET, les deux conditions doivent être __________.","lines":2},
    {"type":"p","text":"Défi facultatif : propose deux essais supplémentaires, juste en dessous et juste au-dessus du seuil. Explique leur intérêt."},
    {"type":"exit","id":"bilan","label":"Billet de sortie individuel, règle corrigée et seuil 30 : donne l'état de la lampe pour (20 ; absence) puis (29 ; présence). Explique pourquoi remplacer ET par OU serait une erreur.","lines":2},
   ],
 ],
 "correction":[
  ["Q1","Le niveau de luminosité et la présence d'une personne. L'action est réalisée par la lampe LED, actionneur de ce modèle."],
  ["Table des essais","Avec OU : allumée, allumée, allumée, éteinte, allumée. Avec ET et < 30 : allumée, éteinte, éteinte, éteinte, éteinte. Les prévisions initiales peuvent être erronées ; elles servent à apprendre."],
  ["Q3","10 sans présence : éclairage inutile. 80 avec présence : assez de lumière mais la lampe s'allume. 30 avec présence : le critère strict < 30 n'est pas satisfait. Un seul contre-exemple expliqué suffit."],
  ["Q4","Répéter en continu : SI luminosité < 30 ET présence détectée ALORS allumer la lampe SINON l'éteindre. La règle initiale OU et sa correction sont simulées sans temporisation ni hystérésis."],
  ["Q5","Lampe éteinte : 30 n'est pas strictement inférieur à 30. Ne pas confondre < et <=."],
  ["Q6","À 40 avec présence : éteinte pour le seuil 30, allumée pour le seuil 50. L'éclairage est alors autorisé dans davantage de situations lumineuses ; cela ne garantit pas une économie d'énergie."],
  ["Synthèse","informations ; traite ; actionneur ; vraies. « Satisfaites » est accepté pour le dernier mot."],
  ["Billet de sortie","(20 ; absence) : éteinte. (29 ; présence) : allumée. OU allumerait aussi avec une seule condition vraie, par exemple dans un couloir sombre mais vide."],
 ],
 "aides":["Pour ET : vérifier séparément les deux conditions et entourer vrai ou faux.","Pour OU : rappeler qu'une condition vraie suffit, y compris lorsque les deux sont vraies.","Fournir l'amorce SI ... ET ... ALORS allumer SINON ... ; faire tester le cas à 30."],
 "vigilance":"La simulation est un modèle simplifié, pas le programme d'un équipement réel. Ne pas appeler lux l'indice 0-100. La séance porte sur la logique de commande ; elle n'enseigne pas encore un langage de programmation complet.",
 "assessment":"Bilan formatif, éventuellement /4 : état de chaque cas 1 point (2 au total) ; explication de l'erreur OU 2 points. Aucun point retiré pour une prévision initiale fausse ensuite corrigée.",
 "next":"Transposer la règle dans un programme par blocs et ajouter une temporisation après le départ de l'utilisateur.",
},
{
 "level":"3e", "slug":"chaines-information-energie", "title":"Un portail, deux chaînes",
 "question":"Comment les chaînes d'information et d'énergie coopèrent-elles dans un portail automatique ?",
 "objective":"Distinguer les deux chaînes, associer des composants à leurs fonctions et expliquer le lien entre ordre et action.",
 "prerequisites":"Reconnaître un moteur et une forme d'énergie électrique ou mécanique. Ne pas supposer les sept fonctions déjà mémorisées.",
 "programme":"Compétences travaillées : analyse du fonctionnement d’un objet, de ses entrées et sorties et de ses flux d’énergie et d’information. Vérifier le rattachement au programme applicable au niveau concerné.",
 "success":["Les trois fonctions de la chaîne d'information et les quatre fonctions de la chaîne d'énergie sont ordonnées.","Le moteur est distingué du capteur ; la conversion électrique vers mécanique est repérée.","L'ordre de commande est relié au module de puissance, puis à l'action sur le portail."],
 "timeline":[
   ["0-7 min","Situation-problème","Demander : « Pourquoi le portail ne se ferme-t-il pas toujours quand on appuie ? Le bouton fournit-il l'énergie qui le déplace ? »"],
   ["7-14 min","Lecture du système","Lire la description et repérer bouton, capteurs, carte, alimentation et moteur. Faire reformuler le modèle de fermeture uniquement."],
   ["14-27 min","Deux chaînes","Répondre à Q1-Q3 et associer les composants aux fonctions. Donner la banque des fonctions ; laisser chercher les associations."],
   ["27-37 min","Essais sur PC","Tester les quatre situations, relever l'ordre et expliquer un arrêt. En binôme, changer de pilote après deux essais."],
   ["37-46 min","Diagnostic et synthèse","Analyser la panne de transmission et la confusion entre courant et information. Compléter la synthèse."],
   ["46-50 min","Correction ciblée","Reprendre le schéma complet et le trajet de l'ordre. Le schéma est fourni dans le guide professeur."],
   ["50-55 min","Bilan individuel","Traiter le billet de sortie, puis télécharger les réponses."],
 ],
 "pages":[
   [
    {"type":"p","text":"Nous étudions un modèle simplifié de portail coulissant, uniquement pendant sa fermeture. Le bouton de fermeture doit rester appuyé. La carte autorise le mouvement si le passage est libre et si le portail n'est pas déjà fermé. Dès qu'une de ces conditions n'est plus respectée, elle demande l'arrêt. Tous les composants sont supposés alimentés et en bon état, sauf dans la question de panne."},
    {"type":"table","headers":["Composant du modèle","Ce qu'il fait"],"rows":[["Bouton de fermeture","Indique la demande de l'utilisateur."],["Cellule de détection","Indique si le passage est occupé."],["Capteur de fin de course","Indique si le portail est complètement fermé."],["Carte programmable","Examine ces informations et décide de l'ordre."],["Liaison de commande","Transmet l'ordre de la carte au module de puissance."],["Bloc d'alimentation 24 V","Fournit l'énergie électrique adaptée à partir du réseau."],["Module de puissance","Autorise ou coupe l'alimentation électrique du moteur selon l'ordre reçu."],["Moteur électrique","Transforme l'énergie électrique en énergie mécanique de rotation."],["Pignon et crémaillère","Transmettent le mouvement au portail et transforment une rotation en translation."]]},
    {"type":"q","id":"q1","label":"1. Quelle action attend-on du système ? Cite deux informations, autres que la demande de l'utilisateur, nécessaires pour l'autoriser.","lines":2},
    {"type":"q","id":"q2","label":"2. Le capteur de fin de course et le moteur ont-ils le même rôle ? Explique ce que chacun fournit.","lines":2},
    {"type":"p","text":"Vocabulaire : un capteur fournit une information ; un actionneur réalise une action grâce à l'énergie reçue. Une translation est un déplacement en ligne droite."},
   ],
   [
    {"type":"h","text":"Construire les deux chaînes"},
    {"type":"p","text":"3. Utilise les composants du document. La chaîne d'information acquiert, traite et communique des informations. La chaîne d'énergie alimente, distribue, convertit et transmet l'énergie nécessaire à l'action."},
    {"type":"diagram","mode":"blank"},
    {"type":"answer_table","id":"chaines","label":"Associe un ou plusieurs composants à chaque fonction.","headers":["Chaîne / fonction","Composant(s)"],"fixed":["Information / acquérir","Information / traiter","Information / communiquer","Énergie / alimenter","Énergie / distribuer","Énergie / convertir","Énergie / transmettre"],"rows":7},
    {"type":"q","id":"q4","label":"4. Quel bloc de la chaîne d'énergie reçoit l'ordre ? Quelle conversion d'énergie a lieu dans le moteur ?","lines":2},
   ],
   [
    {"type":"h","text":"Relier l'ordre à l'action"},
    {"type":"sim","name":"gate"},
    {"type":"answer_table","id":"essais","label":"5. Teste les situations. Indique « fermer » ou « arrêt » et explique un arrêt.","headers":["Bouton / obstacle / déjà fermé","Ordre"],"fixed":["Appuyé / non / non","Appuyé / oui / non","Appuyé / non / oui","Relâché / non / non"],"rows":4},
    {"type":"q","id":"q6","label":"6. Le moteur tourne mais le portail reste immobile. Dans le modèle, le pignon n'engrène plus avec la crémaillère. Quelle fonction est défaillante ? Justifie à partir de l'observation.","lines":3},
    {"type":"q","id":"q7","label":"7. Un élève dit : « Tout ce qui utilise de l'électricité appartient à la chaîne d'énergie. » Explique pourquoi ce raisonnement est faux avec l'exemple de la carte programmable.","lines":3},
    {"type":"q","id":"synthese","label":"Synthèse : la chaîne d'information __________, __________ et __________ les informations. Elle envoie un __________ à la chaîne d'énergie. Celle-ci __________, __________, __________ et __________ l'énergie pour réaliser une __________.","lines":3},
    {"type":"p","text":"À comprendre : les capteurs et la carte ont eux aussi besoin d'énergie pour fonctionner. On les classe ici selon leur rôle dans le système. Une flèche d'information représente un message ou un ordre ; une flèche d'énergie représente un transfert d'énergie. Les pertes d'énergie ne sont pas détaillées dans ce schéma fonctionnel."},
    {"type":"p","text":"Défi facultatif : un obstacle apparaît pendant la fermeture. Décris le chemin allant de sa détection à l'arrêt du mouvement en citant les composants concernés."},
    {"type":"exit","id":"bilan","label":"Billet de sortie individuel : a) classe le capteur et le moteur dans leur chaîne ; b) donne l'énergie reçue et l'énergie utile fournie par le moteur ; c) explique le rôle de l'ordre envoyé par la carte.","lines":3},
   ],
 ],
 "correction":[
  ["Q1","Fermer le portail par coulissement. Il faut savoir si le passage est libre et si le portail est déjà complètement fermé."],
  ["Q2","Le capteur fournit l'information de position fermé/non fermé ; le moteur est un actionneur qui fournit une énergie mécanique de rotation. Le capteur ne fournit pas l'énergie du mouvement."],
  ["Q3, information","Acquérir : bouton, cellule de détection, capteur de fin de course. Traiter : carte programmable. Communiquer : liaison de commande, qui transmet le signal de sortie de la carte."],
  ["Q3, énergie","Alimenter : réseau et bloc d'alimentation 24 V. Distribuer : module de puissance. Convertir : moteur. Transmettre : pignon et crémaillère. Action finale : translation du portail."],
  ["Q4","Le module de puissance, dans la fonction distribuer, reçoit l'ordre. Le moteur convertit l'énergie électrique en énergie mécanique. Une partie est dissipée, notamment sous forme thermique."],
  ["Q5","Ordres dans l'ordre des quatre essais : fermer ; arrêt ; arrêt ; arrêt. Le modèle exige simultanément une demande maintenue, aucun obstacle et une position qui n'est pas déjà fermée."],
  ["Q6","Fonction transmettre défaillante. Le moteur tourne : une conversion vers l'énergie mécanique a lieu, mais le mouvement n'est plus transmis au portail. Dans un système réel, cette observation oriente un diagnostic ; elle ne prouve pas toutes les autres fonctions."],
  ["Q7","La carte est alimentée électriquement mais son rôle étudié est de traiter des informations : elle appartient à la chaîne d'information. Le classement porte sur le rôle et le flux représenté, pas sur la simple présence de courant."],
  ["Synthèse","acquiert ; traite ; communique ; ordre ; alimente ; distribue ; convertit ; transmet ; action. Ne pas placer « agir » comme une conversion supplémentaire : c'est le résultat final."],
  ["Défi","Cellule : détecter ; carte : traiter et demander l'arrêt ; liaison : transmettre l'ordre ; module de puissance : couper l'alimentation du moteur ; arrêt du mouvement dans ce modèle simplifié."],
  ["Billet de sortie","Capteur : information ; moteur : énergie. Énergie électrique reçue, énergie mécanique utile fournie. L'ordre commande le module de puissance pour autoriser ou arrêter l'alimentation du moteur."],
 ],
 "aides":["Donner les sept fonctions dans l'ordre ; demander uniquement l'association des composants.","Faire repérer dans le document les verbes indiquer, décider, transmettre un ordre, fournir l'énergie, transformer et transmettre un mouvement.","Pour la panne : partir du constat « le moteur tourne » et suivre le mouvement vers le portail."],
 "vigilance":"Le bouton est ici une entrée de commande, pas l'interrupteur de puissance du moteur. La fonction communiquer est représentée par la sortie de la carte et sa liaison vers le module de puissance. On peut aussi communiquer vers un utilisateur, mais ce second cas n'est pas étudié. La fermeture réelle d'un portail peut intégrer d'autres sécurités, une inversion et une temporisation ; elles sont hors du modèle.",
 "assessment":"Bilan formatif, éventuellement /6 : classement des deux composants 2 points ; formes d'énergie à l'entrée et à la sortie du moteur 2 points ; ordre relié au module de puissance et à l'action 2 points.",
 "next":"Réinvestir les deux chaînes sur un autre système et réaliser un diagnostic à partir de mesures ou d'observations.",
},
]
